project_id = "sttssfromirzkcqetikq"

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.cashfree-create-order]
verify_jwt = false

[functions.cashfree-verify-order]
verify_jwt = false

