// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uxoqnnybnptujszgndik.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV4b3FubnlibnB0dWpzemduZGlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE3NDg1NzIsImV4cCI6MjA4NzMyNDU3Mn0.YTo5c6MNjMxhA5y_lG5k558CGwcOK_PHprTdKfSlX9o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});